### ISSUE TITLE
State viewer doesn't have contract Cache

### ISSUE THREAD

**Issue by evgenykuzyakov** [near/nearcore#3569]
It will be slow for view RPCs to not have access to compiled contracts.

It seems our only option is to return a compilation error from the view call, if the contract is not already cached.
We also need to introduce a view only version of the cache, that doesn't try to compile a contract if it's not present in the cache.

Introduced by https://github.com/near/nearcore/pull/3310

**Comment by bowenwang1996** [comment]
@olonho is this already fixed?

**Comment by ilblackdragon** [comment]
Is this still true?

**Comment by bowenwang1996** [comment]
I think it is fixed. @olonho please reopen if it is not the case
