### ISSUE TITLE
build fails for v1.22.0

### ISSUE THREAD

**Issue by rencryptofish** [near/nearcore#5452]
running `make release` getting the following build error 

```
error[E0658]: arbitrary expressions in key-value attributes are unstable
 --> runtime/near-vm-errors/src/lib.rs:1:10
  |
1 | #![doc = include_str!("../README.md")]
  |          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  |
  = note: see issue #78835 <https://github.com/rust-lang/rust/issues/78835> for more information
```

**Comment by mina86** [comment]
Could you state which `rustc` version are you using? I.e. output of `rustc --version`?

**Comment by mina86** [comment]
We generally require the latest rustc to compile the code. The actual minimal version the code expects is sest in [rust-toolchain.toml file](https://github.com/near/nearcore/blob/master/rust-toolchain.toml) and at the moment that’s 1.56. The error you’ve quoted indicates that you’re building the code with pre-1.54 compiler. Please update and then you’ll be able to build.

**Comment by rencryptofish** [comment]
ah got it thanks, what about adding something like for node runners:
https://docs.rs/version_check/latest/version_check/

**Comment by mina86** [comment]
There shouldn’t be a need. Cargo should update the toolchain according to the `rust-toolchain.toml`. The reason it didn’t work for you is that prior to [rustup 1.24 (released in April 2021)](https://blog.rust-lang.org/2021/04/27/Rustup-1.24.0.html), the file [was not recognised](https://github.com/rust-lang/rustup/issues/2652) due to `toml` extension. Going forward it’ll work on its own.

**Comment by mina86** [comment]
Actually I lied a bit. `rust-toolchain.toml` will take effect if Rust wast installed through `rustup` only (so for example won’t take effect if it came from system’s package manager). Still, it’s not clear whether adding `build.rs` just to check the version is overall a positive change.
