### ISSUE TITLE
bug: Fix tests not working with python `3.8`

### ISSUE THREAD

**Issue by pmnoxx** [near/nearcore#5499]
Our tests are not compatible with python `3.8` and up. They work with `3.7`.

The command below fails:
```
>>>  python3.8 pytest/tests/sanity/routing_table_sync.py
/home/pmnoxx/repos/nearcore.master/pytest
Traceback (most recent call last):
  File "pytest/tests/sanity/routing_table_sync.py", line 25, in <module>
    from cluster import start_cluster
  File "/home/pmnoxx/repos/nearcore.master/pytest/lib/cluster.py", line 8, in <module>
    import rc
  File "/home/pmnoxx/.local/lib/python3.8/site-packages/rc/__init__.py", line 11, in <module>
    from rc.cache import Cache, CacheCluster
  File "/home/pmnoxx/.local/lib/python3.8/site-packages/rc/cache.py", line 4, in <module>
    from itertools import izip
ImportError: cannot import name 'izip' from 'itertools' (unknown location)
```

This works
```
>>>  python3.7 pytest/tests/sanity/routing_table_sync.py
```
